# This file is part of pikchr.pl.
#
# pikchr.pl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, version 3 of the License.
#
# pikchr.pl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with pikchr.pl. If not, see <https://www.gnu.org/licenses/>.

unstable_features = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
match_block_trailing_comma = true
wrap_comments = true
format_code_in_doc_comments = true
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
imports_layout = "HorizontalVertical"
match_arm_leading_pipes = "Preserve"
