unstable_features = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
match_block_trailing_comma = true
wrap_comments = true
format_code_in_doc_comments = true
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
imports_layout = "HorizontalVertical"
match_arm_leading_pipes = "Preserve"
